language: csharp
solution: SimplePipeline/SimplePipeline.sln
dotnet: 2.0.0
install:
  - nuget restore SimplePipeline/SimplePipeline.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
 - dotnet restore SimplePipeline/SimplePipeline/SimplePipeline.csproj 
 - dotnet build SimplePipeline/SimplePipeline/SimplePipeline.csproj --configuration Release
 - msbuild SimplePipeline/SimplePipeline.sln /t:SimplePipeline_Tests /p:Configuration="Release" /p:Platform="Any CPU"
 - ls -l SimplePipeline/SimplePipeline.Tests/bin/Release
 - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe SimplePipeline/SimplePipeline.Tests/bin/Release/SimplePipeline.Tests.dll