version: 2.0.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore SimplePipeline/SimplePipeline.sln
build:
  project: SimplePipeline/SimplePipeline.sln
  verbosity: minimal
